### ISSUE TITLE
Filling issues for dynaTrace/Dynatrace-Chef cookbook?

### ISSUE THREAD

**Issue by yshoaib** [metmajer/Dynatrace-Chef#1]
[dynaTrace/Dynatrace-Chef](https://github.com/dynaTrace/Dynatrace-Chef) cookbook is a fork of this cookbook, because of which we cannot log issues directly to the former. Is there a reason for the fork? And, where is the best place to log issues; for now, I will be using this repo for that purpose. Thanks.

**Comment by metmajer** [comment]
This one served as a scratchpad, and will go away soon.

**Comment by metmajer** [comment]
Issues are now enabled for our [dynaTrace/Dynatrace-Chef](https://github.com/dynaTrace/Dynatrace-Chef) cookbook.

**Comment by yshoaib** [comment]
@metmajer Thanks!
